//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by hand (will be replaced by controller-gen). DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// --- WormsignDetector ---

// DeepCopyInto copies all fields into another WormsignDetector.
func (in *WormsignDetector) DeepCopyInto(out *WormsignDetector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the WormsignDetector.
func (in *WormsignDetector) DeepCopy() *WormsignDetector {
	if in == nil {
		return nil
	}
	out := new(WormsignDetector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as a runtime.Object.
func (in *WormsignDetector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields into another WormsignDetectorSpec.
func (in *WormsignDetectorSpec) DeepCopyInto(out *WormsignDetectorSpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy returns a deep copy of the WormsignDetectorSpec.
func (in *WormsignDetectorSpec) DeepCopy() *WormsignDetectorSpec {
	if in == nil {
		return nil
	}
	out := new(WormsignDetectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another WormsignDetectorStatus.
func (in *WormsignDetectorStatus) DeepCopyInto(out *WormsignDetectorStatus) {
	*out = *in
	in.WormsignStatus.DeepCopyInto(&out.WormsignStatus)
	if in.LastFired != nil {
		in, out := &in.LastFired, &out.LastFired
		*out = (*in).DeepCopy()
	}
}

// DeepCopy returns a deep copy of the WormsignDetectorStatus.
func (in *WormsignDetectorStatus) DeepCopy() *WormsignDetectorStatus {
	if in == nil {
		return nil
	}
	out := new(WormsignDetectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another WormsignDetectorList.
func (in *WormsignDetectorList) DeepCopyInto(out *WormsignDetectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WormsignDetector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the WormsignDetectorList.
func (in *WormsignDetectorList) DeepCopy() *WormsignDetectorList {
	if in == nil {
		return nil
	}
	out := new(WormsignDetectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as a runtime.Object.
func (in *WormsignDetectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- WormsignGatherer ---

// DeepCopyInto copies all fields into another WormsignGatherer.
func (in *WormsignGatherer) DeepCopyInto(out *WormsignGatherer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the WormsignGatherer.
func (in *WormsignGatherer) DeepCopy() *WormsignGatherer {
	if in == nil {
		return nil
	}
	out := new(WormsignGatherer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as a runtime.Object.
func (in *WormsignGatherer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields into another WormsignGathererSpec.
func (in *WormsignGathererSpec) DeepCopyInto(out *WormsignGathererSpec) {
	*out = *in
	in.TriggerOn.DeepCopyInto(&out.TriggerOn)
	if in.Collect != nil {
		in, out := &in.Collect, &out.Collect
		*out = make([]CollectAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the WormsignGathererSpec.
func (in *WormsignGathererSpec) DeepCopy() *WormsignGathererSpec {
	if in == nil {
		return nil
	}
	out := new(WormsignGathererSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another GathererTrigger.
func (in *GathererTrigger) DeepCopyInto(out *GathererTrigger) {
	*out = *in
	if in.ResourceKinds != nil {
		in, out := &in.ResourceKinds, &out.ResourceKinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Detectors != nil {
		in, out := &in.Detectors, &out.Detectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of the GathererTrigger.
func (in *GathererTrigger) DeepCopy() *GathererTrigger {
	if in == nil {
		return nil
	}
	out := new(GathererTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another CollectAction.
func (in *CollectAction) DeepCopyInto(out *CollectAction) {
	*out = *in
	if in.TailLines != nil {
		in, out := &in.TailLines, &out.TailLines
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the CollectAction.
func (in *CollectAction) DeepCopy() *CollectAction {
	if in == nil {
		return nil
	}
	out := new(CollectAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another WormsignGathererStatus.
func (in *WormsignGathererStatus) DeepCopyInto(out *WormsignGathererStatus) {
	*out = *in
	in.WormsignStatus.DeepCopyInto(&out.WormsignStatus)
}

// DeepCopy returns a deep copy of the WormsignGathererStatus.
func (in *WormsignGathererStatus) DeepCopy() *WormsignGathererStatus {
	if in == nil {
		return nil
	}
	out := new(WormsignGathererStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another WormsignGathererList.
func (in *WormsignGathererList) DeepCopyInto(out *WormsignGathererList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WormsignGatherer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the WormsignGathererList.
func (in *WormsignGathererList) DeepCopy() *WormsignGathererList {
	if in == nil {
		return nil
	}
	out := new(WormsignGathererList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as a runtime.Object.
func (in *WormsignGathererList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- WormsignSink ---

// DeepCopyInto copies all fields into another WormsignSink.
func (in *WormsignSink) DeepCopyInto(out *WormsignSink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the WormsignSink.
func (in *WormsignSink) DeepCopy() *WormsignSink {
	if in == nil {
		return nil
	}
	out := new(WormsignSink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as a runtime.Object.
func (in *WormsignSink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields into another WormsignSinkSpec.
func (in *WormsignSinkSpec) DeepCopyInto(out *WormsignSinkSpec) {
	*out = *in
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(WebhookConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SeverityFilter != nil {
		in, out := &in.SeverityFilter, &out.SeverityFilter
		*out = make([]Severity, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of the WormsignSinkSpec.
func (in *WormsignSinkSpec) DeepCopy() *WormsignSinkSpec {
	if in == nil {
		return nil
	}
	out := new(WormsignSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another WebhookConfig.
func (in *WebhookConfig) DeepCopyInto(out *WebhookConfig) {
	*out = *in
	if in.URLSecretRef != nil {
		in, out := &in.URLSecretRef, &out.URLSecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy returns a deep copy of the WebhookConfig.
func (in *WebhookConfig) DeepCopy() *WebhookConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another WormsignSinkStatus.
func (in *WormsignSinkStatus) DeepCopyInto(out *WormsignSinkStatus) {
	*out = *in
	in.WormsignStatus.DeepCopyInto(&out.WormsignStatus)
	if in.LastDelivery != nil {
		in, out := &in.LastDelivery, &out.LastDelivery
		*out = (*in).DeepCopy()
	}
}

// DeepCopy returns a deep copy of the WormsignSinkStatus.
func (in *WormsignSinkStatus) DeepCopy() *WormsignSinkStatus {
	if in == nil {
		return nil
	}
	out := new(WormsignSinkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another WormsignSinkList.
func (in *WormsignSinkList) DeepCopyInto(out *WormsignSinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WormsignSink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the WormsignSinkList.
func (in *WormsignSinkList) DeepCopy() *WormsignSinkList {
	if in == nil {
		return nil
	}
	out := new(WormsignSinkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as a runtime.Object.
func (in *WormsignSinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- WormsignPolicy ---

// DeepCopyInto copies all fields into another WormsignPolicy.
func (in *WormsignPolicy) DeepCopyInto(out *WormsignPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the WormsignPolicy.
func (in *WormsignPolicy) DeepCopy() *WormsignPolicy {
	if in == nil {
		return nil
	}
	out := new(WormsignPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as a runtime.Object.
func (in *WormsignPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields into another WormsignPolicySpec.
func (in *WormsignPolicySpec) DeepCopyInto(out *WormsignPolicySpec) {
	*out = *in
	if in.Detectors != nil {
		in, out := &in.Detectors, &out.Detectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(PolicyMatch)
		(*in).DeepCopyInto(*out)
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(PolicySchedule)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of the WormsignPolicySpec.
func (in *WormsignPolicySpec) DeepCopy() *WormsignPolicySpec {
	if in == nil {
		return nil
	}
	out := new(WormsignPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another PolicyMatch.
func (in *PolicyMatch) DeepCopyInto(out *PolicyMatch) {
	*out = *in
	if in.ResourceSelector != nil {
		in, out := &in.ResourceSelector, &out.ResourceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.OwnerNames != nil {
		in, out := &in.OwnerNames, &out.OwnerNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of the PolicyMatch.
func (in *PolicyMatch) DeepCopy() *PolicyMatch {
	if in == nil {
		return nil
	}
	out := new(PolicyMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another PolicySchedule.
func (in *PolicySchedule) DeepCopyInto(out *PolicySchedule) {
	*out = *in
	in.Start.DeepCopyInto(&out.Start)
	in.End.DeepCopyInto(&out.End)
}

// DeepCopy returns a deep copy of the PolicySchedule.
func (in *PolicySchedule) DeepCopy() *PolicySchedule {
	if in == nil {
		return nil
	}
	out := new(PolicySchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another WormsignPolicyStatus.
func (in *WormsignPolicyStatus) DeepCopyInto(out *WormsignPolicyStatus) {
	*out = *in
	in.WormsignStatus.DeepCopyInto(&out.WormsignStatus)
	if in.LastEvaluated != nil {
		in, out := &in.LastEvaluated, &out.LastEvaluated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy returns a deep copy of the WormsignPolicyStatus.
func (in *WormsignPolicyStatus) DeepCopy() *WormsignPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(WormsignPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another WormsignPolicyList.
func (in *WormsignPolicyList) DeepCopyInto(out *WormsignPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WormsignPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the WormsignPolicyList.
func (in *WormsignPolicyList) DeepCopy() *WormsignPolicyList {
	if in == nil {
		return nil
	}
	out := new(WormsignPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as a runtime.Object.
func (in *WormsignPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- Common types ---

// DeepCopyInto copies all fields into another WormsignStatus.
func (in *WormsignStatus) DeepCopyInto(out *WormsignStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the WormsignStatus.
func (in *WormsignStatus) DeepCopy() *WormsignStatus {
	if in == nil {
		return nil
	}
	out := new(WormsignStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another SecretReference.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy returns a deep copy of the SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}
